#!bin/bash
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_0.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_1.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_2.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_3.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_4.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_5.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_6.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_1.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_7.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_8.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_9.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_10.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_11.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_12.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_13.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_14.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_15.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_16.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_17.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_18.pairs "-o mean_gt50C"
qsub -V -cwd -pe OpenMP 1 -l mem_free=0.5G,h_rt=10:00:00 single_core_pubdip.sh input/SpeciesCount.count.mean_gt50/SpeciesCount.count.mean_gt50_19.pairs "-o mean_gt50C"


